-- Custom types
create type public.app_permission as enum ('todo.read', 'todo.create', 'todo.update', 'todo.delete', 'user.read', 'user.create', 'user.update', 'user.delete');
create type public.app_role as enum ('admin', 'user');

-- USER ROLES
create table public.user_roles (
  id        bigint generated by default as identity primary key,
  user_uuid   uuid references public.User(uuid) on delete cascade not null,
  role      app_role not null,
  unique (user_uuid, role)
);
comment on table public.user_roles is 'Application roles for each user.';

-- ROLE PERMISSIONS
create table public.role_permissions (
  id           bigint generated by default as identity primary key,
  role         app_role not null,
  permission   app_permission not null,
  unique (role, permission)
);
comment on table public.role_permissions is 'Application permissions for each role.';

insert into public.role_permissions (role, permission)
values
  ('admin', 'todo.read'),
  ('admin', 'todo.create'),
  ('admin', 'todo.update'),
  ('admin', 'todo.delete'),
  ('admin', 'user.read'),
  ('admin', 'user.create'),
  ('admin', 'user.update'),
  ('admin', 'user.delete'),
  ('user', 'todo.read'),
  ('user', 'todo.create'),
  ('user', 'todo.update'),
  ('user', 'todo.delete'),
  ('user', 'user.read');